// Login
export const GET_LOGIN_REQUESTED = "GET_LOGIN_REQUESTED";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILED = "GET_LOGIN_FAILED";
export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS";